version: '3.4'

services:
  php:
    image: mobilife-php-fpm
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - type: bind
        source: .
        target: /srv/blog

  nginx:
    image: mobilife-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./public
        target: /srv/blog/public

#  db:
#    # In production, you may want to use a managed database service
#    image: postgres:9.6-alpine
#    environment:
#        - POSTGRES_DB=blog
#        - POSTGRES_USER=blog
#        # You should definitely change the password in production
#        - POSTGRES_PASSWORD=dbpass
#    volumes:
#      - type: volume
#        source: db-data
#        target: /var/lib/postgresql/data:rw
#    volumes:
#        - db-data:/var/lib/postgresql/data:rw
#        # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#        # - ./docker/db/data:/var/lib/postgresql/data:rw
#    ports:
#        - "5432:5432"
#
#volumes:
#  db-data: